### ISSUE TITLE
Why tikz-nfold.sty?

### ISSUE THREAD

**Issue by astoff** [jonschz/tikz-nfold#1]
This file seems unnecessary. `tikz-cd` has a similar sty file purely due to backward compatibility (the few first versions were not totally generic).

**Comment by jonschz** [comment]
I assumed that a `.sty` file was necessary for CTAN, but this is my first public TeX package so I may lack the experience. I will remove the file for now and reintroduce it if it turns out to be necessary. Thank you for the feedback!
