### ISSUE TITLE
No support for many tikz-cd arrowheads

### ISSUE THREAD

**Issue by varkor** [jonschz/tikz-nfold#5]
At the moment, the tikz-cd arrowhead/tail options such as `maps to`, `tail`, `hook`, `no head`, `two heads`, etc. are ignored. Some of these tikz-nfold has support for with other syntaxes, some are probably harder to support, but it would be nice if it interacted well with tikz-cd without needing to change the syntax.

**Comment by jonschz** [comment]
The best way to tackle this is likely by the restructure in #7, but I will consider adding more arrows by hand if the former turns out not to be feasible.
