### ISSUE TITLE
`dashed` affects arrowhead, not just body

### ISSUE THREAD

**Issue by varkor** [jonschz/tikz-nfold#6]
```tex
\begin{tikzcd}
	\bullet & \bullet
	\arrow[Rightarrow, dashed, from=1-1, to=1-2]
\end{tikzcd}
```
Without nfold:
<img width="105" alt="image" src="https://user-images.githubusercontent.com/3943692/230624990-90271037-615a-4800-beb4-2d6c0409a827.png">
With nfold:
<img width="107" alt="image" src="https://user-images.githubusercontent.com/3943692/230625042-bac9e010-6758-42d9-ab46-5d4643988548.png">
(Also affects `dotted`, etc.)

**Comment by jonschz** [comment]
Thank you for reporting this issue and the extensive testing!
